package com.yc.atcrowdfunding.bean;

public class TProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.id
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.name
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.remark
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.money
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.day
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.status
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.deploydate
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private String deploydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.supportmoney
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Long supportmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.supporter
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Integer supporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.completion
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Integer completion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.memberid
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.createdate
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.follower
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    private Integer follower;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.id
     *
     * @return the value of t_project.id
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.id
     *
     * @param id the value for t_project.id
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.name
     *
     * @return the value of t_project.name
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.name
     *
     * @param name the value for t_project.name
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.remark
     *
     * @return the value of t_project.remark
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.remark
     *
     * @param remark the value for t_project.remark
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.money
     *
     * @return the value of t_project.money
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.money
     *
     * @param money the value for t_project.money
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.day
     *
     * @return the value of t_project.day
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.day
     *
     * @param day the value for t_project.day
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.status
     *
     * @return the value of t_project.status
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.status
     *
     * @param status the value for t_project.status
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.deploydate
     *
     * @return the value of t_project.deploydate
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public String getDeploydate() {
        return deploydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.deploydate
     *
     * @param deploydate the value for t_project.deploydate
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setDeploydate(String deploydate) {
        this.deploydate = deploydate == null ? null : deploydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.supportmoney
     *
     * @return the value of t_project.supportmoney
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Long getSupportmoney() {
        return supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.supportmoney
     *
     * @param supportmoney the value for t_project.supportmoney
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setSupportmoney(Long supportmoney) {
        this.supportmoney = supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.supporter
     *
     * @return the value of t_project.supporter
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Integer getSupporter() {
        return supporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.supporter
     *
     * @param supporter the value for t_project.supporter
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setSupporter(Integer supporter) {
        this.supporter = supporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.completion
     *
     * @return the value of t_project.completion
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Integer getCompletion() {
        return completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.completion
     *
     * @param completion the value for t_project.completion
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setCompletion(Integer completion) {
        this.completion = completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.memberid
     *
     * @return the value of t_project.memberid
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.memberid
     *
     * @param memberid the value for t_project.memberid
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.createdate
     *
     * @return the value of t_project.createdate
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.createdate
     *
     * @param createdate the value for t_project.createdate
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.follower
     *
     * @return the value of t_project.follower
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public Integer getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.follower
     *
     * @param follower the value for t_project.follower
     *
     * @mbggenerated Wed Aug 21 11:28:20 GMT+08:00 2019
     */
    public void setFollower(Integer follower) {
        this.follower = follower;
    }
}