package com.yc.atcrowdfunding.dao;

import com.yc.atcrowdfunding.bean.TAccountTypeCert;
import com.yc.atcrowdfunding.bean.TAccountTypeCertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAccountTypeCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int countByExample(TAccountTypeCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByExample(TAccountTypeCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insert(TAccountTypeCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insertSelective(TAccountTypeCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    List<TAccountTypeCert> selectByExample(TAccountTypeCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    TAccountTypeCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TAccountTypeCert record, @Param("example") TAccountTypeCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TAccountTypeCert record, @Param("example") TAccountTypeCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TAccountTypeCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_type_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKey(TAccountTypeCert record);
}