package com.yc.atcrowdfunding.dao;

import com.yc.atcrowdfunding.bean.TMemberCert;
import com.yc.atcrowdfunding.bean.TMemberCertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int countByExample(TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByExample(TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insert(TMemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insertSelective(TMemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    List<TMemberCert> selectByExample(TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    TMemberCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TMemberCert record, @Param("example") TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TMemberCert record, @Param("example") TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TMemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKey(TMemberCert record);
}