package com.yc.atcrowdfunding.dao;

import com.yc.atcrowdfunding.bean.TMemberAddress;
import com.yc.atcrowdfunding.bean.TMemberAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemberAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int countByExample(TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByExample(TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insert(TMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insertSelective(TMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    List<TMemberAddress> selectByExample(TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    TMemberAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TMemberAddress record, @Param("example") TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TMemberAddress record, @Param("example") TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKey(TMemberAddress record);
}