package com.yc.atcrowdfunding.dao;

import com.yc.atcrowdfunding.bean.TMessage;
import com.yc.atcrowdfunding.bean.TMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    long countByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int deleteByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int insert(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int insertSelective(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    List<TMessage> selectByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    TMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMessage record, @Param("example") TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int updateByExample(@Param("record") TMessage record, @Param("example") TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int updateByPrimaryKeySelective(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Fri Aug 23 14:54:46 CST 2019
     */
    int updateByPrimaryKey(TMessage record);
}