package com.yc.atcrowdfunding.dao;

import com.yc.atcrowdfunding.bean.TProjectType;
import com.yc.atcrowdfunding.bean.TProjectTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProjectTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int countByExample(TProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByExample(TProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insert(TProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insertSelective(TProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    List<TProjectType> selectByExample(TProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    TProjectType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TProjectType record, @Param("example") TProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TProjectType record, @Param("example") TProjectTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKey(TProjectType record);
}