package com.yc.atcrowdfunding.dao;

import com.yc.atcrowdfunding.bean.TProject;
import com.yc.atcrowdfunding.bean.TProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int countByExample(TProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByExample(TProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insert(TProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int insertSelective(TProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    List<TProject> selectByExample(TProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    TProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TProject record, @Param("example") TProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TProject record, @Param("example") TProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Fri Aug 23 09:32:12 GMT+08:00 2019
     */
    int updateByPrimaryKey(TProject record);
}